[package]
name = "code_passenger"
version = "0.1.0"
edition = "2024"

license = "MIT OR Apache-2.0"
description = "code auto documenter"

authors = ["James Hunt <jameshuntdevelopment@gmail.com>"]
repository = "https://github.com/jameshuntt/code_passenger"


[dependencies]
